version: "3.8"
services:
  app:
    image: weather-api    # The app's Docker image, built via Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    ports:
      - 8080:8080         # Expose port 8080 for the app
    restart: "no"

  redis:
    image: redis:latest   # Use the latest official Redis image
    restart: "no"
    ports:
      - 6379:6379