#spring configuration
spring:
  application:
    name: weather-api
  cache:
    type: redis
    redis:
      time-to-live: 3600

  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 5
          min-idle: 1
          max-wait: 2000
      host: ${$REDIS_HOST}
      port: ${$REDIS_PORT}

#weather api key
weather:
  api-key: ${WEATHER_API_KEY}